version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/youtube_tracker
      - REDIS_URL=redis://redis:6379/0
      - YOUTUBE_CLIENT_ID=${YOUTUBE_CLIENT_ID}
      - YOUTUBE_CLIENT_SECRET=${YOUTUBE_CLIENT_SECRET}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - APP_SECRET_KEY=${APP_SECRET_KEY:-dev-secret-key}
      - SESSION_SECRET=${SESSION_SECRET:-dev-session-secret}
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=youtube_tracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build: .
    environment:
      - APP_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/youtube_tracker
      - REDIS_URL=redis://redis:6379/0
      - YOUTUBE_CLIENT_ID=${YOUTUBE_CLIENT_ID}
      - YOUTUBE_CLIENT_SECRET=${YOUTUBE_CLIENT_SECRET}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    depends_on:
      - db
      - redis
    volumes:
      - ./app:/app/app
    command: poetry run python -m app.jobs.worker

volumes:
  postgres_data:
  redis_data:
