# Fly.io deployment configuration for YouTube Disappeared Video Tracker

app = "youtube-tracker"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  SCAN_ENABLED = "false"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    grace_period = "5s"
    interval = "30s"
    method = "GET"
    path = "/healthz"
    protocol = "http"
    timeout = "10s"
    tls_skip_verify = false

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  release_command = "alembic upgrade head"

[[statics]]
  guest_path = "/app/web/static"
  url_prefix = "/static/"
