# Fly.io deployment configuration for YouTube Disappeared Video Tracker

app = "youtube-tracker"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  SCAN_ENABLED = "false"
  PORT = "8080"
  # Slack notification defaults
  SLACK_MIN_SEVERITY = "MEDIUM"
  SLACK_NOTIFICATION_LANGUAGE = "en"
  SLACK_RENOTIFICATION_HOURS = "24"
  SLACK_MAX_NOTIFICATIONS_PER_VIDEO = "3"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 1

[processes]
  app = "uvicorn app.main:app --host 0.0.0.0 --port 8080"

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    path = "/healthz"
    protocol = "http"
    timeout = "10s"
    tls_skip_verify = false
    headers = {}

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[deploy]
  release_command = "alembic upgrade head"
  strategy = "rolling"

[[statics]]
  guest_path = "/app/web/static"
  url_prefix = "/static/"

# Restart policy for resilience
[[restart]]
  policy = "on-failure"
  max_restarts = 3

# Resource limits
[metrics]
  port = 9091
  path = "/metrics"

# Backup configuration
[backup]
  schedule = "0 2 * * *"
