services:
  - type: web
    name: youtube-disappeared-tracker
    env: docker
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SLACK_WEBHOOK_URL
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: APP_SECRET_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: ENV
        value: production
